apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-deletion
  namespace: {{ include "codefresh-runner.namespace" . }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: {{ include "codefresh-runner.serviceAccountName" . }}
      containers:
      - name: codefresh
        image: {{ .Values.image.repository }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/script/delete.sh"]
        env:
          {{- if .Values.env.proxy }}
          {{- range $key, $value := .Values.env.proxy }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end}}
          {{- end}}
          - name: CODEFRESH_TOKEN
            value: {{ .Values.env.codefreshToken }}
          - name: CF_ARG_KUBE_NAMESPACE
            value: {{ include "codefresh-runner.namespace" . }}
          - name: CF_ARG_KUBE_CONTEXT_NAME
            value: inClusterContext
          - name: CF_AGENT_NAME
            value: {{ .Values.env.codefreshAgentName }}
          - name: CF_URL
            value: {{ .Values.env.codefreshURL }}
          - name: CF_ARG_docker-registry
            value: {{ .Values.env.dockerRegistry }}
        volumeMounts:
        - name: delete-script
          mountPath: /script/delete.sh
          subPath: delete.sh
      volumes:
        - name: delete-script
          configMap:
            name: {{ .Release.Name }}-delete-script
            defaultMode: 0777   
      restartPolicy: Never
      {{- if .Values.image.imagePullSecrets }}
      imagePullSecrets:
      {{- range $sec := .Values.image.imagePullSecrets }}
        - name: {{$sec | quote }}
      {{- end }}
      {{- end }}
  backoffLimit: 4