apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-installer-{{ randAlphaNum 5 | lower }}
  labels:
    app: cf-installer
spec:
  restartPolicy: Never
  serviceAccountName: {{ include "codefresh-runner.serviceAccountName" . }}
  containers:
  - name: codefresh     
    image: {{ .Values.installer.image }}
    imagePullPolicy: {{ .Values.installer.imagePullPolicy | default "Always" }}
    command:
    - /usr/local/bin/installer.sh
    {{- if .Release.IsInstall }}
    - init
    {{- end }}
    env:
      {{- if .Values.codefreshTokenSecret }}
      - name: CODEFRESH_TOKEN
        valueFrom:
          secretKeyRef:
            name: {{ required "Require a secret name that contains the codefresh token" .Values.codefreshTokenSecret.name }}
            key: {{ required "Require a secret key that contains the codefresh token" .Values.codefreshTokenSecret.key }}
      {{- end }}
      {{- if .Values.env }}
      {{- range $key, $value := .Values.env }}
      - name: {{ $key }}
        value: {{ $value | quote }}
      {{- end}}
      {{- end}}
    volumeMounts:
    - name: installer-cm
      mountPath: /usr/local/bin/installer.sh
      subPath: installer.sh
    - name: installer-cm
      mountPath: /etc/codefresh/runner-values.yaml
      subPath: runner-values.yaml
  volumes:
    - name: installer-cm
      configMap:
        name: {{ .Release.Name }}-installer
        defaultMode: 0777
  {{- if .Values.installer.imagePullSecrets }}
  imagePullSecrets:
  {{- range $sec := .Values.installer.imagePullSecrets }}
    - name: {{$sec | quote }}
  {{- end }}
  {{- end }}
