apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-upgrade-script
  namespace: {{ include "codefresh-runner.namespace" . }}
data:
  upgrade.sh: |
   #!/bin/bash
   echo "Start Upgrade"
   codefresh version

   echo codefresh auth create-context $CF_ARG_KUBE_CONTEXT_NAME --api-key $CODEFRESH_TOKEN --kube-namespace $CF_ARG_KUBE_NAMESPACE --url $CF_URL
   codefresh auth create-context $CF_ARG_KUBE_CONTEXT_NAME --api-key $CODEFRESH_TOKEN --kube-namespace $CF_ARG_KUBE_NAMESPACE --url $CF_URL
   echo codefresh runner upgrade --y {{ if .Values.env.proxy }}--env-vars NO_PROXY={{ .Values.env.proxy.NO_PROXY | quote }}{{ end}} --agent-name $CF_AGENT_NAME --kube-context-name $CF_ARG_KUBE_CONTEXT_NAME --url $CF_URL --verbose
   codefresh runner upgrade --y {{ if .Values.env.proxy }}--env-vars NO_PROXY={{ .Values.env.proxy.NO_PROXY | quote }}{{ end}} --agent-name $CF_AGENT_NAME --kube-context-name $CF_ARG_KUBE_CONTEXT_NAME --url $CF_URL --verbose

   echo "Finish"